<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AnalysisMode>Recommended</AnalysisMode>
    <RootNamespace>HotRepl.Helpers.Il2Cpp</RootNamespace>
    <AssemblyName>HotRepl.Helpers.Il2Cpp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(Il2CppAssembliesPath)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(MelonLoaderPath)/net6/Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(Il2CppAssembliesPath)/Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
