<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AnalysisMode>Recommended</AnalysisMode>
    <RootNamespace>HotRepl</RootNamespace>
    <AssemblyName>HotRepl.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <!-- WebSocket server -->
    <PackageReference Include="Fleck" Version="1.*" />

    <!-- JSON serialization -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>


  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>HotRepl.BepInEx</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>HotRepl.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
